# XXX/sbt:<java-version>_<sbt-version>
# Check existing versions here: https://XXX:5001/v2/sbt/tags/list

FROM bunyodb/java11:11.0.5
MAINTAINER Connectivity

# Environment variables
ENV SBT_VERSION=1.3.12

USER root
RUN apt-get update && apt-get install -y curl
### 2. Install sbt
RUN curl --silent --show-error --location --fail --retry 3 --output /tmp/sbt.tgz https://piccolo.link/sbt-$SBT_VERSION.tgz \
    && tar -xzf /tmp/sbt.tgz -C /opt/ \
    && rm /tmp/sbt.tgz \
    && /opt/sbt/bin/sbt sbtVersion

### 3. Install required dependencies to build debian packages
RUN apt-get install -y fakeroot lintian

### 4. Update PATH for the tools
ENV PATH="/opt/sbt/bin:$PATH"

ENTRYPOINT ["sbt"]
